apiVersion: apps/v1
kind: Deployment
metadata:
  name: testes-sitecontagem
spec:
  selector:
    matchLabels:
      app: testes-sitecontagem
  replicas: 2
  template:
    metadata:
      labels:
        app: testes-sitecontagem
    spec:
      containers:
        - name: sitecontagem
          image: renatogroffe/sitecontagem-dotnet7-healthcheck:1
          envFrom:
            - configMapRef:
                name: configmap-appconfig-sitecontagem
          ports:
          - containerPort: 80
          livenessProbe:
            httpGet:
              path: /status
              port: 80
            failureThreshold: 2
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: testes-sitecontagem-service
spec:
  selector:
    app: testes-sitecontagem
  ports:
    - port: 80
  type: LoadBalancer